[package]
name = "tlfs-crdt"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
base64 = "0.13.0"
blake3 = "1.0.0"
bytecheck = "0.6.5"
chacha20poly1305 = { version = "0.9.0", features = ["reduced-round"] }
crepe = "0.1.5"
ed25519-dalek = "1.0.1"
getrandom = "0.2.3"
itertools = "0.10.1"
proptest = { version = "1.0.0", optional = true }
range-collections = { version = "0.2.1", features = ["rkyv_validated"], default_features = false }
rkyv = { version = "0.7.18", features = ["validation"] }
sled = { git = "https://github.com/spacejam/sled" }
tracing = "0.1.29"

[dev-dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
proptest = "1.0.0"
